name: blog_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # proximity_sensor: ^1.2.2  
    
  get:
  json_annotation: ^4.3.0

  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  path_provider: ^2.1.3
  dartz: ^0.10.1
  flutter_riverpod: ^2.5.1
  json_serializable: ^6.8.0
  shared_preferences: ^2.2.3
  multi_select_flutter: ^4.1.3
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  awesome_dio_interceptor: ^1.2.0
  equatable: ^2.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  hive_flutter: ^1.1.0
  all_sensors2: ^1.0.1
  test_cov_console: ^0.2.2
  intl: ^0.19.0
  
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  
 
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/blog.jpeg
    - assets/icons/

  fonts:
    - family: Opensans
      fonts:
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
